export const store = [
  { id: 1, name: "Adventure Dress", cost: 2800, type: "dress", img: "https://via.placeholder.com/100"},
  { id: 2, name: "Alplinist Dress", cost: 2520, type: "dress", img: "https://via.placeholder.com/100"},
  { id: 3, name: "Dreamy Dress", cost: 2080, type: "dress", img: "https://via.placeholder.com/100"},
  { id: 4, name: "Frugal Dress", cost: 480, type: "dress", img: "https://via.placeholder.com/100"},
  { id: 5, name: "Checkered Jumper Dress", cost: 1840, type: "dress", img: "https://via.placeholder.com/100"},
  { id: 6, name: "Blossom Tee", cost: 800, type: "top", img: "https://via.placeholder.com/100"},
  { id: 7, name: "Old School Top", cost: 1800, type: "top", img: "https://via.placeholder.com/100"},
  { id: 8, name: "Sailor's Tee", cost: 1050, type: "top", img: "https://via.placeholder.com/100"},
  { id: 9, name: "Checkered Chesterfield Coat", cost: 2380, type: "top", img: "https://via.placeholder.com/100"},
  { id: 10, name: "Detective's Coat", cost: 2500, type: "top", img: "https://via.placeholder.com/100"},
  { id: 11, name: "Dreamy Sweater", cost: 1440, type: "top", img: "https://via.placeholder.com/100"},
  { id: 12, name: "Spider-web Tee", cost: 960, type: "top", img: "https://via.placeholder.com/100"},
  { id: 13, name: "Big Star Tee", cost: 560, type: "top", img: "https://via.placeholder.com/100"},
  { id: 14, name: "Apron Skirt", cost: 700, type: "bottom", img: "https://via.placeholder.com/100"},
  { id: 15, name: "Faux-fur Skirt", cost: 1440, type: "bottom", img: "https://via.placeholder.com/100"},
  { id: 16, name: "Floral Lace Skirt", cost: 1320, type: "bottom", img: "https://via.placeholder.com/100"},
  { id: 17, name: "Frilly Sweat Pants", cost: 880, type: "bottom", img: "https://via.placeholder.com/100"},
  { id: 18, name: "Muay-thai Shorts", cost: 980, type: "bottom", img: "https://via.placeholder.com/100"},
  { id: 19, name: "Blossoming Kimono", cost: 3220, type: "dress", img: "https://via.placeholder.com/100"},
  { id: 20, name: "Bolero Coat", cost: 2080, type: "dress", img: "https://via.placeholder.com/100"},
];
