export const store = [
  { id: 1, name: "Adventure Dress", cost: 2800, type: "dress", img: "./img/dresses/adventuredress.png"},
  { id: 2, name: "Alplinist Dress", cost: 2520, type: "dress", img: "./img/dresses/alpinistdress.png"},
  { id: 3, name: "Dreamy Dress", cost: 2080, type: "dress", img: "./img/dresses/dreamydress.png"},
  { id: 4, name: "Frugal Dress", cost: 480, type: "dress", img: "./img/dresses/frugaldress.png"},
  { id: 5, name: "Checkered Jumper Dress", cost: 1840, type: "dress", img: "./img/dresses/checkeredjumperdress.png"},
  { id: 6, name: "Blossom Tee", cost: 800, type: "top", img: "./img/tops/blossomtee.png"},
  { id: 7, name: "After-school jacket", cost: 1050, type: "top", img: "./img/tops/afterschooljacket.png"},
  { id: 8, name: "Sailor's Tee", cost: 1050, type: "top", img: "./img/tops/sailorstee.png"},
  { id: 9, name: "Checkered Chesterfield Coat", cost: 2380, type: "top", img: "./img/tops/checkeredchesterfieldcoat.png"},
  { id: 10, name: "Detective's Coat", cost: 2500, type: "top", img: "./img/tops/detectivescoat.png"},
  { id: 11, name: "Dreamy Sweater", cost: 1440, type: "top", img: "./img/tops/dreamysweater.png"},
  { id: 12, name: "Spider-web Tee", cost: 960, type: "top", img: "./img/tops/spiderwebtee.png"},
  { id: 13, name: "Big Star Tee", cost: 560, type: "top", img: "./img/tops/bigstartee.png"},
  { id: 14, name: "Graduation gown", cost: 3360, type: "top", img: "./img/tops/graduationgown.png"},
  { id: 15, name: "Chef's outfit", cost: 1680, type: "top", img: "./img/tops/chefsoutfit.png"},
  { id: 16, name: "Retro sweater", cost: 1200, type: "top", img: "./img/tops/retrosweater.png"},
  { id: 17, name: "Bomber-style jacket", cost: 1440, type: "top", img: "./img/tops/bomberstylejacket.png"},
  { id: 18, name: "Noble Coat", cost: 4800, type: "top", img: "./img/tops/noblecoat.png"},
  { id: 19, name: "Blossoming Kimono", cost: 3220, type: "dress", img: "./img/dresses/blossomingkimono.png"},
  { id: 20, name: "Bolero Coat", cost: 2080, type: "top", img: "./img/tops/bolerocoat.png"},
];
